### ISSUE TITLE
Refactor RecipeStatus as functional component

### ISSUE THREAD

**Issue by jayarnielsen** [jayarnielsen/recipe-lab#41]
Refactor RecipeStatus as a functional component that uses react and Apollo hooks APIs.

**Comment by mahimshridhar** [comment]
can i take this ?

**Comment by mahimshridhar** [comment]
im getting Project not found: 'default@default' error in my terminal after setting up, any idea why ?

**Comment by mahimshridhar** [comment]
nevermind, i figured it out

**Comment by jayarnielsen** [comment]
Hi Mahim, that would be great! Let me know if you have any questions or any issues with the setup
